version: 2.1

jobs:
  # Run vite build step via npm
  production-build:
    docker:
      - image: cimg/node:19.3.0 # Node v.19.3.0 
    working_directory: ~/lphaapcom/app/
    steps:
      - checkout:
          path: ~/lphaapcom/
      - run:
          name: "Install packages"
          command: "npm ci"
      - run:
          name: "Vite build"
          command: "npm run build"
  # SSH to server to ping deployment script
  production-deploy:
    steps:
      run:
        name: "Run server deploy"
        command: ssh admin@lphaap.com


workflows:
  # Run vite build on resources
  build:
    jobs:
      - production-build

  # Run vite build on resources
    deploy:
      jobs:
        - production-deploy