version: 2.1

jobs:
  # Run vite build step via npm
  vite-build:
    docker:
      - image: cimg/node:18.16.0 # Node v.18.16.0 
    steps:
      - checkout
      - run:
          name: "Vite build"
          command: "npm run build"

workflows:
  # Run vite build on resources
  build-workflow:
    jobs:
      - build
