version: 2.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:current

  node-executor:
    docker:
      - image: cimg/node:19.3.0 # Node v.19.3.0

jobs:
  # Run vite build step via npm
  production-build:
    executor: node-executor
    working_directory: ~/lphaapcom/app/
    steps:
      - checkout:
          path: ~/lphaapcom/
      - run:
          name: "Install packages"
          command: "npm ci"
      - run:
          name: "Vite build"
          command: "npm run build"

  # SSH to server to ping deployment script
  production-deploy:
    executor: ubuntu-executor
    steps:
      - run:
        command: echo $DEPLOY_USER
      - run:
        command: echo $DEPLOY_HOST
      #- run:
      #    name: "Run SSH deploy"
      #    command: ssh $DEPLOY_USER@$DEPLOY_HOST


workflows:
  build-and-deploy:
    jobs:
      #- production-build
      - production-deploy
          #requires:
          #- production-build
