version: 2.1

jobs:
  # Run vite build step via npm
  production-build:
    docker:
      - image: cimg/node:19.3.0 # Node v.19.3.0 
    working_directory: ~/lphaapcom/app/
    steps:
      - checkout:
          path: ~/lphaapcom/
      - run:
          name: "Install packages"
          command: "npm ci"
      - run:
          name: "Vite build"
          command: "npm run build"
  # SSH to server to ping deployment script
  production-deploy:
    steps:
      - run:
        name: "Run SSH deploy"
        command: ssh DEPLOY_USER@$DEPLOY_HOST


workflows:
  # Run vite build on resources
  build-and-deploy:
    jobs:
      - production-build
      - production-deploy:
          requires:
          - build
