name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
          node-version: 16
          cache: npm
          cache-dependency-path: app/package-lock.json
    - name: Install Dependencies
      run: |
            npm ci
    - name: Build Project
      run: |
            npm run build --if-present

  securityscan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'