name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
          node-version: 16
          cache: npm
          cache-depedency-path: app/package-lock.json
    - name: Install Dependencies
      run: |
            npm ci
    - name: Build the project
      run: |
            npm run build --if-present